services:
  web_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: compose_web_lab_compose_tf06
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db_cache
    depends_on:
      - db_cache

  db_cache:
    image: redis:alpine
    container_name: compose_db_lab_compose_tf06
    volumes:
      - redis_data_lab_compose_tf06:/data

volumes:
  redis_data_lab_compose_tf06:
    driver: local